name: 'Chromatic'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Verify public directory
        run: |
          ls -la public/images || (mkdir -p public/images && echo "Created public/images directory")

      - name: Build Storybook
        run: npm run build-storybook
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la storybook-static
          echo "Checking for images..."
          find storybook-static -type f -name "*.png"

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
          exitOnceUploaded: true
          exitZeroOnChanges: true